class Scheme

  INFINITE_BOUNCE = 'INFINITE_BOUNCE'
  INFINITE_POUNCE = 'INFINITE_POUNCE'

  ROLLING_BOUNCE  = 'ROLLING_BOUNCE'
  ROLLING_POUNCE  = 'ROLLING_POUNCE'

  INFINITE = [
    INFINITE_BOUNCE,
    INFINITE_POUNCE
  ]

  def self.is_infinite? scheme
    INFINITE.include? scheme
  end
end